# Generated by Django 4.0.4 on 2022-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_plan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
